### PR TITLE
Move to KDE plasma 6

### PR DESCRIPTION
**Pull request by bouteillerAlan**

### CODE REVIEW

**Comment by luisbocanegra** [comment]
Got it mostly working
- Had to use a dummy fullRepresentation for some reason
- moved the tooltip to main 
- And get the values out of compact using property changed signals
- Only thing left I think is figuring out why the refresh icon doesn't work

image

**Comment by bouteillerAlan** [comment]
Hey @luisbocanegra can you mind sharing your code ? :smiley: 

I think we have to move all the logic into `main.qml` and put the "visual" in the compact and full representation file.

**Comment by luisbocanegra** [comment]
Pushed, but just realized I was making my changes against feat/plasma6 and not feat/kde6 🤦‍♂️

**Comment by luisbocanegra** [comment]
I moved the tooltop fix to the correct branch, now the refresh icon works too!

> I think we have to move all the logic into `main.qml` and put the "visual" in the compact and full representation file.

Probably, if there was a lot more variables shared between components the current approach would get messy

**Review by bouteillerAlan — COMMENTED** [review]
Looks good to me, any update to do @luisbocanegra ?
If not, we can merge, and I can update the store :D

**Comment by luisbocanegra** [comment]
Ship it!

**Pull request merged**
