### PR TITLE
QA branch for V4.1.1

### PR DESCRIPTION
**Pull request by bouteillerAlan**
Features :
 - [x] #12 by @luisbocanegra - show the applet in the systray
 - [x] #11 by @luisbocanegra - improve the ui of the applet
 - [x] #14 #16 by @bouteillerAlan @luisbocanegra - add count option and add aur & arch count w/ option to merge
 - [x] by @bouteillerAlan @luisbocanegra - add the possibility to show a dot in place of the label and add a color picker for the dot
 - [x] by @luisbocanegra @bouteillerAlan - add information into the tooltips

Todo : 
- [X] fix size and label (close this item because I'm ok with the result so far and I don't want to take more time for it)
- [x] add theme color for the dot
- [x] add the value in the tooltips (`x update form core and extra \n y update form aur & other` or `arch: x \n other: y`)
- [x] update author list
- [x] update feature and setting list
- [x] update readme for in tray activation
- [x] update screenshot
- [x] ~update version (to 4.1.1)~ version to 4.2.0 considering the number of new features
- [x] resolve that https://github.com/bouteillerAlan/archupdate/pull/13#issuecomment-1794429256

### CODE REVIEW

**Comment by bouteillerAlan** [comment]
Hey @luisbocanegra many thanks for this update, seem amazing :)

Do you think is possible to add an option for the systray ? 

I don't know if it's a good idea to activate it by default, for example I like to position it where I want in my taskbar. Is it possible to add an "enable in systray" option or not at all? What do you think?

**Comment by luisbocanegra** [comment]
> Do you think is possible to add an option for the systray ?
> 
> I don't know if it's a good idea to activate it by default, for example I like to position it where I want in my taskbar.

Thinking more about it I agree with you, better allow system tray but not enabled by default out and let the user to decide where to place the applet

> Is it possible to add an "enable in systray" option or not at all? What do you think?

I don't think so, the only way would be with [dbus activation](https://develop.kde.org/docs/plasma/widget/properties/#x-plasma-dbusactivationservice).

Closest thing is `Plasmoid.status` to control whether it shows or not but only if is enabled by default (to e.g. make the widget appear only if there are updates and hide in the expanded area or even disappear from the tray otherwise).

**Comment by bouteillerAlan** [comment]
Need to test something for the height of the icon, add an option for the size maybe
image

**Comment by bouteillerAlan** [comment]
Bug when I add the applet to a vertical taskbar 
```sh
file:///home/a2n/.local/share/plasma/plasmoids/a2n.archupdate.plasmoid/contents/ui/archupdate.qml:14:37: QML Compact: Cannot specify left, right, horizontalCenter, fill or centerIn anchors for items inside Row. Row will not function.
```

**Comment by luisbocanegra** [comment]
> Need to test something for the height of the icon, add an option for the size maybe image image

Maybe limit the badge width too

image

**Comment by luisbocanegra** [comment]
> Bug when I add the applet to a vertical taskbar
> 
> ```shell
> file:///home/a2n/.local/share/plasma/plasmoids/a2n.archupdate.plasmoid/contents/ui/archupdate.qml:14:37: QML Compact: Cannot specify left, right, horizontalCenter, fill or centerIn anchors for items inside Row. Row will not function.
> ```
> 
> Seem to be that line (the commented one) in Compact.qml :
> 
> ```qml
>   Item {
>     id: container
>     height: row.itemSize
>     width: row.width
> 
>     //anchors.centerIn: parent
> 
>     Components.PlasmoidIcon {
> ```

Yeah, to be honest I tend to use anchors when they are probably not required. Is Row needed for something you have planned? `Item` seems to work fine as the Compact.qml root element

**Comment by luisbocanegra** [comment]
> For some reason when I added the applet to the vertical taskbar the count is not update
> The screenshot
> image
> 
> But the cmd is launch normally (the log is only for the applet in the vertical bar), no problems with the horizontal bar 🤔 image

Here it is
Vertical badge `text` needs to take `generateResult()` or make `generateResult()` change `totalText` so it only called once

```
    WorkspaceComponents.BadgeOverlay { // for the horizontal bar
      anchors {
        bottom: container.bottom
        right: container.right
      }
      text: generateResult()
      visible: !isPanelVertical
      icon: updateIcon
    }

    WorkspaceComponents.BadgeOverlay { // for the vertical bar
      anchors {
        verticalCenter: container.bottom
        right: container.right
      }
      text: totalText
      visible: isPanelVertical
      icon: updateIcon
    }
```

**Comment by bouteillerAlan** [comment]
> > Bug when I add the applet to a vertical taskbar
> > ```shell
> > file:///home/a2n/.local/share/plasma/plasmoids/a2n.archupdate.plasmoid/contents/ui/archupdate.qml:14:37: QML Compact: Cannot specify left, right, horizontalCenter, fill or centerIn anchors for items inside Row. Row will not function.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Seem to be that line (the commented one) in Compact.qml :
> > ```qml
> >   Item {
> >     id: container
> >     height: row.itemSize
> >     width: row.width
> > 
> >     //anchors.centerIn: parent
> > 
> >     Components.PlasmoidIcon {
> > ```
> 
> Yeah, to be honest I tend to use anchors when they are probably not required. Is Row needed for something you have planned? `Item` seems to work fine as the Compact.qml root element

Yeah, that the tutorial code haha :laughing: I'm going to replace it with Item :)

**Comment by bouteillerAlan** [comment]
> > Bug when I add the applet to a vertical taskbar
> > ```shell
> > file:///home/a2n/.local/share/plasma/plasmoids/a2n.archupdate.plasmoid/contents/ui/archupdate.qml:14:37: QML Compact: Cannot specify left, right, horizontalCenter, fill or centerIn anchors for items inside Row. Row will not function.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Seem to be that line (the commented one) in Compact.qml :
> > ```qml
> >   Item {
> >     id: container
> >     height: row.itemSize
> >     width: row.width
> > 
> >     //anchors.centerIn: parent
> > 
> >     Components.PlasmoidIcon {
> > ```
> 
> Yeah, to be honest I tend to use anchors when they are probably not required. Is Row needed for something you have planned? `Item` seems to work fine as the Compact.qml root element

Who okai my code is not good at all haha (I have made only half of the thing I wanted to do with the function) I have made a refacto.

**Comment by luisbocanegra** [comment]
> > Need to test something for the height of the icon, add an option for the size maybe image image
> 
> Maybe limit the badge width too
> 
> image

A bunch of ideas

* Scale down badge as needed
* Use some padding to move the badge down a bit
* Make the icon smaller in the tray so the badge covers less of it
* Limit the badge width to a specific length, combine count if exceeded
* Replace badge with icon + count for widget and icon only for tray

Here a screenshot of badge scaled up/down manually and some padding on top, unfortunately breaks consistency and also is less readable.
image

**Comment by bouteillerAlan** [comment]
I have made some edit, I think like that the height and the width is more consistent, for the moment I have done nothing for the label ^^

widget in taskbar : 
image

in the systray : 
image
image

**Comment by bouteillerAlan** [comment]
Ok I have added the possibility to use a dot in place of the label. Because in any case if the text is too long in the label it will be unmanageable.
image
image
image

**Comment by luisbocanegra** [comment]
> Ok I have added the possibility to use a dot in place of the label. Because in any case if the text is too long in the label it will be unmanageable.
> 
> The color is editable via the setting, but I need your help for matching the theme color if the setting is set to a empty string :
> 
> ```qml
>     Rectangle {
>       visible: dot
>       height: container.height / 2.5
>       width: height
>       radius: height / 2
>       color: dotColor === '' ? dotColor : dotColor // todo - add theme color if dotColor === ''
>       anchors {
>         right: container.right
>         bottom: container.bottom
>       }
>     }
> ```
> 
> Any idea ? I'm testing with `kirigami.theme` ([pointieststick.com/2023/06/14/call-to-action-easy-porting-opportunity-in-plasma](https://pointieststick.com/2023/06/14/call-to-action-easy-porting-opportunity-in-plasma/)).
> 
> image image image

While `Kirigami.Theme.textColor` works (the svs use `textColor` too). 
For plasma 5 is better to use `PlasmaCore.Theme.textColor` so it correctly follows either the plasma theme colors or current color scheme, and then switch to Krigami.Theme for plasma 6.

```qml
import org.kde.kirigami 2.20 as Kirigami
...
    Rectangle {
      visible: dot && isUpdateNeeded()
      height: container.height / 2.5
      width: height
      radius: height / 2
      color: dotColor === '' ? PlasmaCore.Theme.textColor : dotColor
      anchors {
        right: container.right
        bottom: container.bottom
      }
    }
```

**Comment by luisbocanegra** [comment]
* [x] add theme color for the dot

Also changed the color text field to a color picker

image

**Comment by luisbocanegra** [comment]
* [ ] add the value in the tooltips

Which one looks better? I like 3 for how compact it is.

1. Screenshot_20231106_144512

2. Screenshot_20231106_145139

3. Screenshot_20231106_145334

* Other

**Comment by bouteillerAlan** [comment]
> * [ ]  add the value in the tooltips
> 
> Which one looks better? I like 3 for how compact it is.
> 
> 1. Screenshot_20231106_144512
> 2. Screenshot_20231106_145139
> 3. Screenshot_20231106_145334
> 
> * Other

Yes the 3 is very cool :) Thanks a lot for all the help !

**Comment by luisbocanegra** [comment]
> > * [ ]   add the value in the tooltips
> > 
> > Which one looks better? I like 3 for how compact it is.
> > 
> > 1. Screenshot_20231106_144512
> > 2. Screenshot_20231106_145139
> > 3. Screenshot_20231106_145334
> > 
> > 
> > * Other
> 
> Yes the 3 is very cool :) Thanks a lot for all the help !

No problem!

There is a small issue with the tooltip, when the mouse enters the widget it displays the default one, and then moving more into the widget displays the custom one 🙃. 

Will push in a moment, maybe you can figure out why

**Comment by bouteillerAlan** [comment]
> > > * [ ]    add the value in the tooltips
> > > 
> > > Which one looks better? I like 3 for how compact it is.
> > > 
> > > 1. Screenshot_20231106_144512
> > > 2. Screenshot_20231106_145139
> > > 3. Screenshot_20231106_145334
> > > 
> > > 
> > > * Other
> > 
> > 
> > Yes the 3 is very cool :) Thanks a lot for all the help !
> 
> No problem!
> 
> There is a small issue with the tooltip, when the mouse enters the widget it displays the default one, and then moving more into the widget displays the custom one 🙃.
> 
> Will push in a moment, maybe you can figure out why

FYI the issue is only present in systray (horizontal or vertical).

**Comment by luisbocanegra** [comment]
> > There is a small issue with the tooltip, when the mouse enters the widget it displays the default one, and then moving more into the widget displays the custom one 🙃.
> > Will push in a moment, maybe you can figure out why
> 
> FYI the issue is only present in systray (horizontal or vertical). I'm looking into the clipboard code for any hints on how kde dev do that :)

> https://invent.kde.org/plasma/plasma-workspace/-/tree/Plasma/5.27/applets/clipboard?ref_type=heads

I think that one is more limited, I used Tooltip.qml here https://github.com/luisbocanegra/plasma-intel-gpu-monitor can you check if it has the same issue?

Could do myself but I'm currently on Plasma master (trying to port https://github.com/psifidotos/applet-window-title lol) and this thing breaks if I switch to Plasma 5 until next reboot

**Comment by bouteillerAlan** [comment]
> > > There is a small issue with the tooltip, when the mouse enters the widget it displays the default one, and then moving more into the widget displays the custom one 🙃.
> > > Will push in a moment, maybe you can figure out why
> > 
> > 
> > FYI the issue is only present in systray (horizontal or vertical). I'm looking into the clipboard code for any hints on how kde dev do that :)
> 
> > https://invent.kde.org/plasma/plasma-workspace/-/tree/Plasma/5.27/applets/clipboard?ref_type=heads
> 
> I think that one is more limited, I used Tooltip.qml here https://github.com/luisbocanegra/plasma-intel-gpu-monitor can you check if it has the same issue?
> 
> Could do myself but I'm currently on Plasma master (trying to port https://github.com/psifidotos/applet-window-title lol) and this thing breaks if I switch to Plasma 5 until next reboot

The problem seem resolve with that, but the width is messed up : https://invent.kde.org/plasma/plasma-workspace/-/blob/Plasma/5.27/applets/digital-clock/package/contents/ui/main.qml?ref_type=heads#L82

Yes same with the v0.1.1, I think we have to use `Plasmoid.toolTipItem`

**Comment by bouteillerAlan** [comment]
@luisbocanegra  I have updated the code in 94e5103 for test if you want, rest to pass the total value to the tooltips if everything is ok for you :)

**Comment by luisbocanegra** [comment]
> @luisbocanegra I have updated the code in [94e5103](https://github.com/bouteillerAlan/archupdate/commit/94e5103ad612e1c5530a06f484575e80dbf07f15) for test if you want, ~rest to pass the total value to the tooltips if everything is ok for you :)~ (done in [e73e136](https://github.com/bouteillerAlan/archupdate/commit/e73e136d12d9b18607fefd9344b242c814b745ee))

Oh it worked? Interesting

**Comment by bouteillerAlan** [comment]
> > @luisbocanegra I have updated the code in [94e5103](https://github.com/bouteillerAlan/archupdate/commit/94e5103ad612e1c5530a06f484575e80dbf07f15) for test if you want, ~rest to pass the total value to the tooltips if everything is ok for you :)~ (done in [e73e136](https://github.com/bouteillerAlan/archupdate/commit/e73e136d12d9b18607fefd9344b242c814b745ee))
> 
> Oh it worked? Interesting

Why ? 😂

**Comment by luisbocanegra** [comment]
> > > @luisbocanegra I have updated the code in [94e5103](https://github.com/bouteillerAlan/archupdate/commit/94e5103ad612e1c5530a06f484575e80dbf07f15) for test if you want, ~rest to pass the total value to the tooltips if everything is ok for you :)~ (done in [e73e136](https://github.com/bouteillerAlan/archupdate/commit/e73e136d12d9b18607fefd9344b242c814b745ee))
> > 
> > 
> > Oh it worked? Interesting
> 
> Why ? 😂

Looks weird

**Comment by bouteillerAlan** [comment]
> > > > @luisbocanegra I have updated the code in [94e5103](https://github.com/bouteillerAlan/archupdate/commit/94e5103ad612e1c5530a06f484575e80dbf07f15) for test if you want, ~rest to pass the total value to the tooltips if everything is ok for you :)~ (done in [e73e136](https://github.com/bouteillerAlan/archupdate/commit/e73e136d12d9b18607fefd9344b242c814b745ee))
> > > 
> > > 
> > > Oh it worked? Interesting
> > 
> > 
> > Why ? 😂
> 
> Looks weird but if it works it works 😆

that a bug ? no it's a feature !

**Comment by luisbocanegra** [comment]
Just tested all the options and panel locations, everything seems to be working correctly.

**Comment by bouteillerAlan** [comment]
> Just tested all the options and panel locations, everything seems to be working correctly.

Ok ! Me too, so let's go for a release I think :)

**Comment by bouteillerAlan** [comment]
Release done @luisbocanegra, again thanks you so much for the help 🍻

**Comment by luisbocanegra** [comment]
You're welcome!

**Pull request merged**
